### ISSUE TITLE
Cant stream other hardware audio devices

### ISSUE THREAD

**Issue by MrPicaroon** [TheEpicSnowWolf/TheEpicAudioStreamer#4]
I can stream only virtual audio cable other devices like VoiceMeeter devices "VB-Audio VoiceMeeter AUX VAIO - VoiceMeeter Aux Input (VB-Audio VoiceMeeter AUX VAIO)" not work.

![image](https://user-images.githubusercontent.com/53136475/196311793-51671a0f-3773-4ff5-8717-44abc491b5f6.png)

My Windows Version: Windows 11

**Comment by TheEpicSnowWolf** [comment]
Heya, I don't seem to be able to reproduce this. I can pick both physical and virtual audio devices and the capturing works. In the title of the issue you indicate that you try to stream from an hardware output, however in the text you say you can't stream from the VoiceMeeter Input, which is a virtual audio device, could you clarify on that please?

I think it's been a literal decade since I used VoiceMeeter last, so would be great if you could provide some additional info on what you're using the VoiceMeeter Aux Input for? Also, this seems obvious, but have you double-checked if sound is actually coming through the audio devices that you are testing?

**Comment by MrPicaroon** [comment]
Heyo, thanks for replying. Let me show what actually i wanna do with my bad screenshot :)
![image](https://user-images.githubusercontent.com/53136475/196529731-51b5605b-4f1f-4ed6-bd29-1620e7edd1f7.png)

Bot should be do stream my "VB-Audio VoiceMeeter AUX VAIO - VoiceMeeter Aux Input (VB-Audio VoiceMeeter AUX VAIO)" cuz i`m route my mic and spotify to this hardware. "virtual audio cable" i`m using only for spotify. If i use "virtual audio cable" i cant route my mic sound to "virtual audio cable" its impossible. 

I need a basic discord bot where we can use 2 commands /join and /leave
I wanna that bot because i need a make Discord Radio Program where people can add to their discord server for listening me live when i`m live :)

I have tried a other discord bots and there is work "VB-Audio VoiceMeeter AUX VAIO - VoiceMeeter Aux Input (VB-Audio VoiceMeeter AUX VAIO)" good. But Interfaces and coding so bad, simple they dont have / commands.

Your Bot is pretty cool. Thats way i wanna contact with you about this problem.

**Comment by TheEpicSnowWolf** [comment]
I don't think this setup is working quite as you intend it to. The way that you are currently using VoiceMeeter, you are routing your mic to the VoiceMeeter Output B1, and Spotify to the VoiceMeeter Output B2. The virtual AUX device is an input for VoiceMeeter, so whatever application uses this is an output sends its sound to VoiceMeeter, preparing it for further mixing (currently being sent to hardware output A1). So what you have currently set up is this: 
![image](https://user-images.githubusercontent.com/6506715/196548585-f3ec11b2-6c25-4346-8648-ca4fc98643cf.png)

So the only audio that you will hear by capturing the VoiceMeeter AUX Input device is the one that other applications send to this output device (note the terminology: It's an output device because it's meant to be used by other applications as an output, but it's called VoiceMeeter AUX _Input_, because it will routed _into_ VoiceMeeter).

Your Mic and Spotify are not actually being mixed down into the VoiceMeeter AUX Input, which is why you won't hear them when you select it as a device for the bot. Your best chance is probably to route everything that you want to stream to Discord to a physical output device (A1-A5) that you are not actively using, and then selecting this as a device that the bot is supposed to capture the audio from.

You could for example set Spotify to use one of the VoiceMeeter virtual inputs (so VoiceMeeter VAIO, VoiceMeeter AUX or VoiceMeeter VAIO3) as an output device. This would free up the Virtual Audio Cable to be used as a physical output device on for example A2 which you can then use with the bot.

In any case, this seems more like an issue with the way VoiceMeeter is set up than the bot I'm afraid. I can recommend [this video ](https://www.youtube.com/watch?v=ytMt68Pl1OQ) for a deep dive into how VoiceMeeter routing works.

**Comment by MrPicaroon** [comment]
Thanks again for your answer. But then I had a question. With the same settings, it works fine with the AUX device in other bots. What could be the reason for this? For example, I have a bot coded on JAVA and it works without sound problems with these settings.

**Comment by MrPicaroon** [comment]
Heeey yo, i fix that. 
I just add to A2 Hardware Out Virtual Cable and perfect work.

Can i ask, how you build a project without dll`s a single exe files ? when i try there a more DLL`s
I use Visual Studio.

I`m try to Costura.Foby extension but there now this files https://www.youtube.com/watch?v=jeghRQHjnSo&ab_channel=IronShell

![image](https://user-images.githubusercontent.com/53136475/196571018-4ee3667b-2534-4a9b-996f-472433e8eb99.png)

How i can make it only 1 exe like your Released project ? :) Sorry cuz i`m noob at coding i wanna make a single exe and share with my DJ`s to use bot on their PC`s

**Comment by TheEpicSnowWolf** [comment]
When you publish your project in Visual Studio, in the Publishing Profile there's an option to "produce single file"
![image](https://user-images.githubusercontent.com/6506715/196789699-95efdcc7-e644-4d63-b00d-745c5d0806fc.png)
It will still generate the pdb file, but you can delete that.
